/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorProducto;
import controlador.ControladorUsuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.Usuario;

/**
 *
 * @author rodri
 */
public class ListaProductos extends javax.swing.JFrame {

    /**
     * Creates new form ListaProductos
     */
    public ListaProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_img = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_filtrar = new javax.swing.JButton();
        btn_todos = new javax.swing.JButton();
        btn_volveralmenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_producto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/xamp (1).png"))); // NOI18N
        lbl_img.setText("ss");

        btn_salir.setBackground(new java.awt.Color(255, 128, 0));
        btn_salir.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_filtrar.setBackground(new java.awt.Color(255, 128, 0));
        btn_filtrar.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn_filtrar.setText("Filtrar por Stock");
        btn_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtrarActionPerformed(evt);
            }
        });

        btn_todos.setBackground(new java.awt.Color(255, 128, 0));
        btn_todos.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn_todos.setText("Todos");
        btn_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todosActionPerformed(evt);
            }
        });

        btn_volveralmenu.setBackground(new java.awt.Color(255, 128, 0));
        btn_volveralmenu.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn_volveralmenu.setText("volver al menu");
        btn_volveralmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volveralmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_todos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btn_filtrar)
                .addGap(18, 18, 18)
                .addComponent(btn_volveralmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_img)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_todos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_volveralmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btn_filtrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbl_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Stock_min", "Stock_act", "Tipo_Producto"
            }
        ));
        jScrollPane1.setViewportView(tbl_producto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todosActionPerformed
        
        
        
        
       ControladorProducto cl = new ControladorProducto();
       ArrayList<Producto> misProductos = cl.traerProducto();
       //obtener el modelo de la tabla
       DefaultTableModel modeloTabla = (DefaultTableModel) tbl_producto.getModel();

       //Dejamos el modelo sin registros
       modeloTabla.setRowCount(0);
       
       for(Producto pro : misProductos)
       {
           int codigo = pro.getCodigo();
           String descripcion = pro.getDescripcion();
           int precio = pro.getPrecio();
           int stock_min=pro.getStock_min();
           int stock_act =pro.getStock_act();
           String tipo_producto=pro.getTipo_producto();
           
           
           //crear registro del arraylist a la tabla 
           modeloTabla.addRow(new Object[]{codigo, descripcion, precio, stock_min, stock_act, tipo_producto});
        }

       
        
    }//GEN-LAST:event_btn_todosActionPerformed

    private void btn_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtrarActionPerformed
        // TODO add your handling code here:
         
       ControladorProducto cl = new ControladorProducto();
       ArrayList<Producto> misProductos = cl.filtrarPorStock();
       //obtener el modelo de la tabla
       DefaultTableModel modeloTabla = (DefaultTableModel) tbl_producto.getModel();

       //Dejamos el modelo sin registros
       modeloTabla.setRowCount(0);
       
       for(Producto pro : misProductos)
       {
           int codigo = pro.getCodigo();
           String descripcion = pro.getDescripcion();
           int precio = pro.getPrecio();
           int stock_min=pro.getStock_min();
           int stock_act =pro.getStock_act();
           String tipo_producto=pro.getTipo_producto();
           
           
           //crear registro del arraylist a la tabla 
           modeloTabla.addRow(new Object[]{codigo, descripcion, precio, stock_min, stock_act, tipo_producto});
        }
    }//GEN-LAST:event_btn_filtrarActionPerformed

    private void btn_volveralmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volveralmenuActionPerformed
        // TODO add your handling code here:
        Menu menu=new Menu();
          
          menu.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btn_volveralmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_filtrar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_todos;
    private javax.swing.JButton btn_volveralmenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTable tbl_producto;
    // End of variables declaration//GEN-END:variables
}
